<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.examples.com/wsdl/WSAutenticacion.wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSAutenticacion" targetNamespace="http://www.examples.com/wsdl/WSAutenticacion.wsdl">
  <message name="WSAutenticacionRequest">
    <part name="usuario" type="xsd:string"/>
    <part name="clave" type="xsd:string"/>
  </message>
  <message name="WSAutenticacionResponse">
    <part name="autorizado" type="xsd:boolean"/>
  </message>
  <portType name="WSAutenticacion_PortType">
    <operation name="autenticar">
      <input message="tns:WSAutenticacionRequest"/>
      <output message="tns:WSAutenticacionResponse"/>
    </operation>
  </portType>
  <binding name="WSAutenticacion_Binding" type="tns:WSAutenticacion_PortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="autenticar">
      <soap:operation soapAction="autenticar"/>
      <input>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:examples:wsautenticacion" use="encoded"/>
      </input>
      <output>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:examples:wsautenticacion" use="encoded"/>
      </output>
    </operation>
  </binding>
  <service name="WSAutenticacion_Service">
    <documentation>WSDL File for WSAutenticacion</documentation>
    <port binding="tns:WSAutenticacion_Binding" name="WSAutenticacion_Port">
      <soap:address location="http://127.0.0.1:8095/sap-autenticacion/services/WSAutenticacion_Port"/>
    </port>
  </service>
</definitions>
