
package co.edu.javeriana.modval.servicio.sap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSAutenticacion_PortType", targetNamespace = "http://www.sap.servicio.com/wsdl/WSAutenticacion.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WSAutenticacionPortType {


    /**
     * 
     * @param clave
     * @param usuario
     * @return
     *     returns boolean
     */
    @WebMethod(action = "autenticar")
    @WebResult(name = "autorizado", partName = "autorizado")
    public boolean autenticar(
        @WebParam(name = "usuario", partName = "usuario")
        String usuario,
        @WebParam(name = "clave", partName = "clave")
        String clave);

}
