<definitions name="Autenticacion"
	targetNamespace="http://www.sap.com/wsdl/Autenticacion.wsdl" xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.sap.com/wsdl/Autenticacion.wsdl"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pay="http://www.sap.com/schemas">

	<types>
		<xsd:schema xmlns:pay="http://www.sap.com/schemas">
			<xsd:import schemaLocation="../xsd/Autenticacion.xsd"
				namespace="http://www.sap.com/schemas" />
		</xsd:schema>
	</types>

	<message name="Validacion">
		<part name="Input" element="pay:Cliente" />
	</message>

	<message name="RespuestaValidacion">
		<part name="Input" element="pay:ResultadoValidacion" />
	</message>

	<portType name="AutenticacionInterface">
		<operation name="Validar">
			<input message="tns:Validacion" />
			<output message="tns:RespuestaValidacion" />
		</operation>
	</portType>

	<binding name="Autenticacion_Binding" type="tns:AutenticacionInterface">
		<soap:binding style="rpc"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="Validar">
			<soap:operation soapAction="validar" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<service name="ServicioAutenticacion">
		<documentation>WSDL File for Autenticacion</documentation>
		<port binding="tns:Autenticacion_Binding" name="AutenticacionInterface">
			<soap:address location="http://www.sap.com/Autenticacion/" />
		</port>
	</service>
</definitions>