<?xml version="1.0" encoding="UTF-8"?>

<definitions
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
  targetNamespace="http://www.sap.servicio.com/wsdl/WSAutenticacion.wsdl"
  xmlns:tns="http://www.sap.servicio.com/wsdl/WSAutenticacion.wsdl"
  name="WSAutenticacion">
  <message name="WSAutenticacionRequest">
    <part name="usuario" type="xsd:string"/>
    <part name="clave" type="xsd:string"/>
  </message>
  <message name="WSAutenticacionResponse">
    <part name="autorizado" type="xsd:boolean"/>
  </message>
  <portType name="WSAutenticacion_PortType">
    <operation name="autenticar">
      <input message="tns:WSAutenticacionRequest"/>
      <output message="tns:WSAutenticacionResponse"/>
    </operation>
  </portType>
  <binding name="WSAutenticacion_Binding" type="tns:WSAutenticacion_PortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="autenticar">
      <soap:operation soapAction="autenticar"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="WSAutenticacion_Service">
    <documentation>WSDL File for WSAutenticacion</documentation>
    <port binding="tns:WSAutenticacion_Binding" name="WSAutenticacion_Port">
      <soap:address location="http://localhost:9030/sap-autenticacion/WSAutenticacion/"/>
    </port>
  </service>
</definitions>